config/routes.rb
CapstoneWebsite::Application.routes.draw do

  root to: 'static_pages#home'

  resources :mail_messages, only: [:new, :create]

  match 'blog', to: 'static_pages#blog'
  match 'resume', to: 'static_pages#resume'
  match 'pictures', to: 'static_pages#pictures'
  match 'contact', to: 'mail_messages#new'

end

app/models/mail_message.rb
class MailMessage < ActiveRecord::Base
  has_no_table

  column :name, :string
  column :email, :string
  column :message, :string
  validates_presence_of :name, :email, :message

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mail_messages_controller.rb
class MailMessagesController < ApplicationController
  def new
    @mail_message = MailMessage.new
  end

  def create
    @mail_message = MailMessage.new(params[:mail_message])
    if(ContactMailer.contact_message(@mail_message).deliver)
      redirect_to contact_path
      abort 'as;dlkaf;sfj'
    else
      render :new
      abort 'nooooooooooooo'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def blog
  end

  def resume
  end

  def pictures
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="bar-top"></div>
  <div class="bar-bottom">
    <p>David Ferris - Capstone 2014 &nbsp &nbsp &nbsp | &nbsp &nbsp &nbsp <em>Updated 2/5/2014</em></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<%= render 'layouts/navigation' %>
<div class="header-bar"></div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default no-padding" role="navigation">
  <div class="navbar-header">
    <div class="navbar-brand">Capstone 2014</div>
  </div>

  <ul class="nav navbar-nav">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Blog', blog_path %></li>
    <li><%= link_to 'Resume', resume_path %></li>
    <li><%= link_to 'Pictures?', pictures_path %></li>
    <li><%= link_to 'Contact Me', contact_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <%= yield %>

  <%= render 'layouts/footer' %>
</body>
</html>

app/views/mail_messages/new.html.erb
<% provide :title, 'Capstone 2014 | Contact' %>

<div class="content">
  <div class="banner">
    <h1>CONTACT ME</h1>
  </div>

  <div class="divider"></div>

  <div class="form-fields">
    <%= simple_form_for :mail_message do |f| %>
      <%= f.input :name, input_html: { class: 'contact-input line name' }, label: false, placeholder: 'Full Name' %>
      <%= f.input :email, input_html: { class: 'contact-input line email' }, label: false, placeholder: 'Email Address' %>
      <%= f.input :message, as: :text, input_html: { class: 'contact-input area' }, label: false, placeholder: 'Type your message here..' %>
      <%= f.submit 'Send', class: 'btn btn-primary submit' %>
    <% end %>
      <button class="btn btn-default clear">Clear</button>
  </div>

  <div class="clearfix"></div>

  <div class="divider"></div>

  <em id='contact-text'>If you do not wish to use the form, feel free to contact me at dave.ferris@snc.edu</em>
</div>

app/views/static_pages/blog.html.erb
<% provide :title, 'Capstone 2014 | Blog' %>

<div class="content">
  <div class="banner">
    <h1>BLOG</h1>
  </div>

  <div class="divider"></div>

  <div class="blog-entry">
    <em>February 1, 2014</em>
    <p>
      Today I continued to expand upon my basic site design. I adjusted the styles of my general page template, created styles for the blog page, and fomatted blog entries. I have also created shells for the resume and gallery pages, and will fill these pages out in the near future. Certain aspects of the site (philosophy, blog, etc.) must be completed by Thursday of next week (2/6/2014), so I will need to focus on writing content for those areas.
    </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<% provide :title, 'Capstone 2014 | Home' %>

<div class="content">
  <div class="banner">
    <h1>VISUALIZING TEXT</h1>
  </div>

  <div class="divider"></div>

  <div class="gallery">
    <div class="gallery-main">
      <div id="large1" class="gallery-large">
        <%= image_tag 'placeholder1.jpg', alt: 'main image' %>
      </div>

      <div id="large2" class="gallery-large">
        <%= image_tag 'placeholder2.jpg', alt: 'main image' %>
      </div>

      <div id="large3" class="gallery-large">
        <%= image_tag 'placeholder3.jpg', alt: 'main image' %>
      </div>

      <div id="large4" class="gallery-large">
        <%= image_tag 'placeholder4.jpg', alt: 'main image' %>
      </div>
    </div>

    <ul class="gallery-slides">

      <li id="image1" class="gallery-small inactive">
        <div class="overlay"></div>
        <%= image_tag 'placeholder1-small.jpg', alt: 'first image' %>
      </li>

      <li id="image2" class="gallery-small inactive">
        <div class="overlay"></div>
        <%= image_tag 'placeholder2-small.jpg', alt: 'second image' %>
      </li>

      <li id="image3" class="gallery-small inactive">
        <div class="overlay"></div>
        <%= image_tag 'placeholder3-small.jpg', alt: 'third image' %>
      </li>

      <li id="image4" class="gallery-small inactive">
        <div class="overlay"></div>
        <%= image_tag 'placeholder4-small.jpg', alt: 'fourth image' %>
      </li>

    </ul>


  </div>

  <div class="clearfix"></div>

  <div class="divider"></div>

  <div class="features">
    <div class="half-content left">
      <h3>About the Project</h3>
      <p>&nbsp &nbsp Online surveys often have open-ended questions or comment sections with text fields. When hundreds or
          thousands of people take the survey, how are those administering the survey supposed to gauge the results without
          reading each survey, one-by-one?</p>
      <p>&nbsp &nbsp The goal of my project is to analyze a large sample of text and identify key words/phrases and the frequencies
          with which they occur. This way, I will be able to provide a visual representation of the words/phrases that are used most
          frequently, which will make it quick and easy to gain a general overview of the text. In the case of a survey, this would
          be useful to represent the opinions of the surveyed population</p>
      <p>&nbsp &nbsp I am planning to first write an application in C++ that will accept a text file (or many) as input, filter the text, and
          create a data structure (most likely a heap) containing words and their frequencies. I have chosen C++ for two reasons:
        <p>
          1.) I have more experience with C++ than I do with any other language.
        </p>

        <p>
          2.) I believe that C++ is a good language for analyzing text and for managing data structures.
        </p>

        <p>
          &nbsp &nbsp I am then planning to use a language such as Javascript to create a visual representation of the data. This will be determined
          after I have completed the data management portion of the project.
        </p>
      </p>

    </div>

    <div class="half-content right">
      <h3>Philosophy</h3>
      <p>&nbsp &nbsp My first exposure to computer science came when I was about 8 or 9 years old, watching my brother write
          text-based games in Q-Basic. At the time, I found programming to be boring; too much hunting and pecking for
          too small of a result. I didn't delve into programming again until my first semester at SNC.</p>
      <p>&nbsp &nbsp I began my time at SNC as a physics major, which didn't last very long. CS110 was a requirement for the physics
          program, and after 7 weeks of C++, I was a computer science major. I was drawn to the field of computer science by
          the addictiveness of coding. The freedom that comes with coding - being able to accomplish goals via a large variety
          of ways - gives the feeling that you can make almost anything you want to. Some weekends I would think of an idea for
          a program and then spend hours working on it, just on a whim. The addictiveness of coding has motivated me to
          pursue a career in software development.</p>
      <p>&nbsp &nbsp Another aspect of computer science that draws me in is the rapidly-advancing nature of the field. It seems like every-other
          day there has been an advancement in technology or a software innovation that allows for a range of further innovation. You
          never know what is going to be possible in the next 10 years, 5 years, or even the next year. I can't think of many other
          professions where this is the case.</p>
    </div>

    <div class="clearfix"></div>
  </div>

</div>

app/views/static_pages/pictures.html.erb
<% provide :title, 'Capstone 2014 | Pictures' %>

<div class="content">
  <div class="banner">
    <h1>PICTURES</h1>
  </div>

  <div class="divider"></div>

  <h2>Pictures may be added in the near future</h2>

  <div class="divider"></div>
</div>

app/views/static_pages/resume.html.erb
<% provide :title, 'Capstone 2014 | Resume' %>

<div class="content">
  <div class="banner">
    <h1>RESUME</h1>
  </div>

  <div class="divider"></div>

  <div class="embedded-resume">
    <%= image_tag 'Ferris_David_Resume-resized.jpg', alt: 'Resume' %>
    <div class="clearfix"></div>
    <span>
      <%= link_to 'View and Download the PDF Version', asset_path('Ferris_David_Resume.pdf'), target: '_blank' %>
      &nbsp &nbsp
      <em>Last Updated 2/4/2014</em>
    </span>
  </div>


</div>